image: node:latest

variables:
  production: "true"

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn install
  - yarn run build
  - yarn run docs
  - cp -R whitepaper dist/
  - rm -rf public
  - mv dist public

  artifacts:
    paths:
    - public
  
  only:
  - master